#!/bin/bash

if [ $# -lt 2 ] ; then
    cat << EOF
NAME:
  modify_nasm   ---- 修整格式并生成合适的nasm文件

SYNOPSIS:
  modify_nasm -f s_file -o output_file   

OPTIONS:
    -f    ------   the path of assembly file
    -o    ------   the file name of the output_file

EXAMPLE
    modify_nasm2 -f ./hook_src -o hookFs.nasm
EOF
    exit 0
fi

while getopts ":f:o:" opt;
do 
   case $opt in 
      f ) s_file=$OPTARG ;;
      o ) nasm_file=$OPTARG ;;
      ? ) echo "error"
          exit 1;;

  esac
done

cat $s_file > /tmp/hookFs0.s

sed '1,6d' -i /tmp/hookFs0.s

sed 's/0000.... <//g' /tmp/hookFs0.s | sed 's/>:/:/g' | sed 's/[0-9a-f]*:.\{22,22\}//g' | sed 's/<.*>//g' | sed 's\ PTR \\g'| sed 's/jle  /&0x/g' | sed 's/0x\s\s/  0x/g' | sed 's/je   /&0x/g' | sed 's/0x\s\s/  0x/g' | sed 's/jne  /&0x/g' | sed 's/0x\s\s/  0x/g' | sed 's/jmp  /&0x/g' | sed 's/0x\s\s/  0x/g'| sed 's/jns  /&0x/g' | sed 's/0x\s\s/  0x/g' | sed 's/\+eiz\*1//g' | sed '/ds/d' | sed '/ret/abcdefg' | sed '/bcdefg/,/^$/d' | sed '/ret/G' | sed 's/call /&0x/g' | sed 's/0x\s\s/ 0x/g' >  /tmp/test2.nasm


echo -e "global _start\nsection .text" > /tmp/header

cat /tmp/header /tmp/test2.nasm  > $nasm_file

