# Makefile - makefile for target/src/vxcom/debug
#
# modification history
# --------------------
# 01d,17oct01,dbs  improve build rules to allow for veloce hacks
# 01c,11oct01,nel  Include defs file by default as it's required by SIMNT
#                  build.
# 01b,16jul01,dbs  simplify makefile structure
# 01a,19jun01,nel  written.
#
# DESCRIPTION
# This file contains the makefile rules for building the vx library
#

DEFS_VXCOM = $(WIND_BASE)/target/h/make/defs.vxcom
include $(DEFS_VXCOM)
include $(VXCOM_BASE)/h/make/rules.library.$(VXDCOM_BUILD_HOST)
